### ISSUE TITLE
The term 'Roku:' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by UladzKha** [adheus/vs-roku-development#2]
Hi, when i try to execute one of extension command:

1. Roku: Deploy

2. Roku: Debug console 

3. Roku: Deploy & Debug 

i get this error: 

> Roku: : The term 'Roku:' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Please check [This my question on stackoverflow](https://stackoverflow.com/questions/60094352/how-to-deploy-roku-app-using-visual-studio-code-extension) for more details.

**Comment by limatheusm** [comment]
Did you try to use the shortcut `Cmd+Shift+P` (`Ctrl` if you're on Windows) ?

1. `Cmd+Shift+P`
2. Type `Roku: Deploy`

**Comment by UladzKha** [comment]
Oh god, yes it works, i did it via cmd, thank you for your answer!
